version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: finances_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finances
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # A Mágica: O Docker vai ler o teu schema.sql e criar as tabelas sozinho!
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql 

volumes:
  postgres_data: